spring.application.name=demo
spring.data.mongodb.uri=mongodb+srv://paf:paf123@cluster0.0vfmwfr.mongodb.net/smart_campus_db?authSource=admin&retryWrites=true&w=majority

spring.security.oauth2.client.registration.google.client-id=71813655033-f7ecaeickeklunjpujusunn621b8dv4e.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
app.frontend.url=http://localhost:3000

# Error handling
server.error.include-message=always
server.error.include-binding-errors=always
server.error.include-stacktrace=on_param
server.error.include-exception=false

# Static resources
spring.web.resources.static-locations=classpath:/static/
spring.web.resources.cache.period=3600